### ISSUE TITLE
ドキュメントの誤植(?)について

### ISSUE THREAD

**Issue by yu-kara420s** [meti-dx-team/METI-Digital-Tools#1]
素晴らしいドキュメントの公開ありがとうございます。ところで、P.7に「限られた範囲内においては依然としてだと考えられる。」という部分がありますが、これは「限られた範囲内においては依然として有効だと考えられる。」でしょうか？（単なる誤植だと思いますが、入る言葉によって意味が異なる部分なので確認をさせていただきました）

**Comment by tishii0305** [comment]
早速のご連絡、ありがとうございます。
申し訳ございません、ご認識のとおりです。
ご指摘ありがとうございます。

**Comment by tishii0305** [comment]
先ほど誤植を含めた軽微な修正版をアップいたしました。
ご確認頂ければと思います。

以下に同一の報告書を公開しております。
https://www.meti.go.jp/meti_lib/report/2020FY/000143.pdf

**Comment by yu-kara420s** [comment]
ご対応、ありがとうございます。修正いただいていることを確認いたしました。
